### ISSUE TITLE
WETH -> wstETH pricing is inverted with wrappers enabled

### ISSUE THREAD

**Issue by blakearnold** [1inch/spot-price-aggregator#145]
When quoting mainnet WETH (0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2) -> wstETH (0x7f39c581f595b53c5cb19bd0b3f8da6c935e2ca0) the price returned is inverted and instead returns the wstETH -> WETH price when wrappers are enabled.

wstETH -> WETH is correct
<img width="569" alt="Screenshot 2024-05-20 at 3 59 59 PM" src="https://github.com/1inch/spot-price-aggregator/assets/136089/da939ae6-48a5-4cb6-bc11-717813d70040">
WETH -> wstETH should be inverted, but is not
<img width="558" alt="Screenshot 2024-05-20 at 3 59 18 PM" src="https://github.com/1inch/spot-price-aggregator/assets/136089/37a72c38-3ca7-4cbb-b5d9-db6c3262cea4">

This is not an issue without wrappers:
<img width="593" alt="Screenshot 2024-05-20 at 4 02 18 PM" src="https://github.com/1inch/spot-price-aggregator/assets/136089/d6cbe545-296b-4a74-ad13-559017aef95a">
<img width="593" alt="Screenshot 2024-05-20 at 4 02 39 PM" src="https://github.com/1inch/spot-price-aggregator/assets/136089/899fd30e-bf12-4291-a34b-b7c10c30913a">

**Comment by zZoMROT** [comment]
Indeed, it seems there is a problem with the use of wrappers for `dstToken`. Thank you for identifying and highlighting this.

**Comment by zZoMROT** [comment]
The bug has been fixed in the new version of `OffchainOracle`. The new address of the main contract is:

- `0xf224a25453D76A41c4427DD1C05369BC9f498444` on all networks
- `0xdCa3e52Af86F8244fd0EDA8064Dc30E154d93033` on the zkSync network

Thank you for the improvement suggestion!

<img width="657" alt="weth_wsteth" src="https://github.com/1inch/spot-price-aggregator/assets/3616087/75188308-389b-4e99-8d28-2ca0d5ff5cd8">
<img width="672" alt="wsteth_weth" src="https://github.com/1inch/spot-price-aggregator/assets/3616087/81bbcb8b-08f5-498e-969e-ded2ca84dd51">
