### ISSUE TITLE
Cant price AMBO on polygon

### ISSUE THREAD

**Issue by blakearnold** [1inch/spot-price-aggregator#158]
Seeing issues pricing AMBO (0x9B8B6A1298d34B3c4bBDDce8a7fF0149121592C1) on polygon.
There is a quickswap pool (AMBO/USDC native) - https://dexscreener.com/polygon/0x6e8e0683e3e98302e2d44c44e191e4c47a72590e
but getting a 0 price back even after adding native as a custom connector

<img width="579" alt="Screenshot 2024-06-26 at 12 41 13 PM" src="https://github.com/1inch/spot-price-aggregator/assets/136089/437eead4-e705-40e7-a8c2-e54dd1159603">

**Comment by zZoMROT** [comment]
Thank you for highlighting the issue.

The problem lies in the `QuickSwap` factory used in `SpotPriceAggregator`. This [factory](https://polygonscan.com/address/0x5757371414417b8C6CAad45bAeF941aBc7d3Ab32#readContract) is a contract that is a fork of `UniswapV2`, and indeed, the [pool](https://polygonscan.com/address/0x6e8E0683e3e98302e2d44C44E191E4C47A72590E#readContract) with `AMBO` is not present in this factory.
This pool is in a different [factory](https://polygonscan.com/address/0x411b0fAcC3489691f28ad58c47006AF5E3Ab3A28#readContract), which likely belongs to a newer version of the `QuickSwap`. Therefore, a new oracle needs to be added for `QuickSwap`. I have created a task for this.

If you have the time and willingness, you are welcome to contribute to this update.

**Comment by blakearnold** [comment]
This pool [quickswap v3](https://docs.quickswap.exchange/technical-reference/smart-contracts/v3), where it looks like the current oracle is quickswap v2.

Might be as simple as deploying a uniswap v3 like oracle with the correct params. I'll can take a stab at finding these params

**Comment by blakearnold** [comment]
Quickswap v3 actually forks Algebra Integral contracts, [docs on the difference](https://docs.algebra.finance/algebra-integral-documentation/algebra-integral-technical-reference/integration-process/migration-from-uniswapv3) between uniswap v3.

2 important differences:
- pool address derivation logic is different
- only 1 pool per pair

Thinking I need to create a new AlgebraLikeOracle.sol, which will look similar to UniswapV3LikeOracle.sol, but with an updated `_getPool` function and `getRate` wont need to loop through `fees[]`.

**Comment by zZoMROT** [comment]
Thank you for your research! This saved me time!
This is my cry of the soul - why they changed `slot0()` to `globalState()` in pools 😭
I will do this in the coming days as soon as I decide the best approach – whether to add a separate oracle with duplicate code or to make changes to the `UniswapV3LikeOracle`.

**Comment by blakearnold** [comment]
Great! Thanks for building and maintaining this repo, these contracts are amazing at getting accurate reference prices

**Comment by zZoMROT** [comment]
It's already fixed. Thank you for the improvement suggestion!
<img width="687" alt="Screenshot" src="https://github.com/1inch/spot-price-aggregator/assets/3616087/1f66bc28-4db7-4980-a3eb-44c0e673aa8f">
