### ISSUE TITLE
why this token has no rate in the oracle?

### ISSUE THREAD

**Issue by wangereth** [1inch/spot-price-aggregator#171]
token: 0x7122985656e38BDC0302Db86685bb972b145bD3C
<img width="704" alt="image" src="https://github.com/user-attachments/assets/31b87dcd-3b45-48a8-8101-a9bc244d57c9">
there is uniswap v3 pool of it.
https://etherscan.io/address/0xf577068c05fda48ba1729c9a190f78008c1f11a2

**Comment by zZoMROT** [comment]
Thank you for your question and for your interest in our project. The reason this token has no rate in the oracle is that the current state of the pool indicates there is no liquidity. To determine this, you can follow these steps:
- Use the `slot0()` method in the pool to get the current tick.
- With the obtained tick number, call the `ticks(tick)` method to get details about the tick.
- You will see that there is no liquidity in the current tick.

Since the pool's current state shows no liquidity, there is no price available. If this pool was created by you, you need to delve into how UniswapV3 works and properly add liquidity to ensure it is available across all ticks, or manage it correctly when liquidity was added to specific ticks.
