### ISSUE TITLE
How to obtain the historical price of a token?

### ISSUE THREAD

**Issue by CSWellesSun** [1inch/spot-price-aggregator#193]
I have an archive node, and when I try to call this function with the blockNumber set to a block from three months ago, I can't get the price. However, when I set it to a block which is 200 blocks from now, I am able to retrieve it. Why is that? How can I obtain the historical price of a token about 3-4 months ago?

**Comment by zZoMROT** [comment]
The issue here is that the latest version of the oracle contract was deployed in transaction (for instance, this [tx](https://etherscan.io/tx/0x92b2468bc445ae33741f5c880449b00e29f54b3bd3bf31ffa01c787cda3b5707) for mainnet) on August 15, 2024. At the block you're querying from three months ago, this contract simply didn't exist yet.

To resolve this, you have a couple of options:

- Use one of the previous versions of the oracle contract (you can find these in the "**Prev oracle versions (legacy)**" section in the README for all networks).
- Alternatively, though more resource-intensive and slower, you could try forking the network at the desired block (e.g., using Hardhat), deploy the latest oracle on the fork, configure it with current settings (or your custom config), and then retrieve the token prices from the fork.

Hope this helps! If you find a more efficient way to access historical data before the oracle's initial deployment, please share it; it could be beneficial for others as well. 

If you have any further questions or issues, I'm happy to help.
