### ISSUE TITLE
RPC timeout while doing multicall on `aggregator` on local forks

### ISSUE THREAD

**Issue by Aviksaikat** [1inch/spot-price-aggregator#87]
I may be doing this wrong but I think there is an issue when performing multicall `aggregator` contract. The weird part is while performing a single call to just the `getRate` or `getRateToEth`  functions it works sometimes, but takes 4-5 mins. But when it comes to multicall ganache/hardhat all make `Time out error`.

## Poc:
- Performed multicall on mainnet which works just fine
![image](https://github.com/1inch/spot-price-aggregator/assets/31238298/e0c3191c-dc99-4c60-b9bd-ae6309e08bf4)

- Mainnet-fork using `anvil` 
![image](https://github.com/1inch/spot-price-aggregator/assets/31238298/b82f4af3-d0d1-4bd4-ab27-a1ed29ea1274)

## My environment
- OS: Linux: Debian
- Framework: brownie & apeworx

**Comment by zZoMROT** [comment]
Thank you for bringing up this issue. When you're using Hardhat's forking feature to interact with the network, the number of different contracts you're touching in your query can greatly affect the performance. The more state data you're touching across various contracts in your RPC call, the longer it will take to complete the operation. This is because a copy of the blockchain state for all affected contracts is being made during your call.

### Recommendations:

1. **For View Calls:** If you're only using `view` calls in your case, try bypassing forking and connect directly to the desired network. This should expedite query processing.

2. **Timeout Issue:** If you're testing your functionality and getting a "Time Out Error", you can increase the timeout setting in your `hardhat.config.js` like so:

```
mocha: {
    timeout: 90000, // or whatever time you find suitable
}
```
