### ISSUE TITLE
Which price does spot-price-aggregator returns, last, ask or else?

### ISSUE THREAD

**Issue by AlwxDavydov** [1inch/spot-price-aggregator#93]
I fetch price data of coin AGI (0x818835503F55283cd51A4399f595e295A9338753) using price for requiested tokens(https://portal.1inch.dev/documentation/spot-price/swagger). And 1inch api return this 
![image](https://github.com/1inch/spot-price-aggregator/assets/111245305/0cdd89a2-d631-4b5a-b6c0-2dd9b8b905ed)
At the same time on 1inch web price is a bit different 
![image](https://github.com/1inch/spot-price-aggregator/assets/111245305/0ba67c1f-c1ed-4cd5-98f0-6ec1666d0a0c)
The price of last deal is also different 
![image](https://github.com/1inch/spot-price-aggregator/assets/111245305/fe63ba19-a7b3-4ff3-b50c-1679278087ed)
Moreover, when it comes to pancake, the price of LP tokens is also distinct. Consequently, I find it challenging to determine which price the requested tokens will return. I believe that the difference in the USDT-USD price has a minor impact, as on the Binance Smart Chain (BSC), USDT currently equals 0.9998 USD, and the difference is relatively small at present. It's worth noting that in all my price calculations, I've consistently used the USDT price for AGI, always considering it as 1 USDT. Additionally, it's possible that the quantity of coins for the swap could influence the price, although this is not the case here. Furthermore, this matter has already been addressed in an open ticket.

I also want to mention that I picked AGI cause it only has one pair on defi (on pancake with USDT). Thats why the situation is not clear to me. How can 3 sources receiving the price from the same path have 3 different numbers

**Comment by zZoMROT** [comment]
When you pull token prices through the 1inch API, the service, using `OffchainOracle`, initially pegs the price to WETH (or WBNB for your BSC network scenario). Then, this figure is scaled by the price of ETH (or BNB for the BSC network) in US dollars. Given that the prices of ETH and BNB are notoriously volatile and in constant flux, you’re likely to see subtle discrepancies in prices at different moments in time.

The discrepancies in prices that you notice between the API, the 1inch website, and other sources, can arise due to this volatility, and also because different sources acquire and update their pricing data differently. This may include variations in calculation methods, liquidity, and trading volumes across different platforms and liquidity pools. However, since you mentioned that there is only one pool with your token, this does not apply to your situation, but bear this in mind in other instances.

For obtaining the most precise and up-to-the-minute price data that isn’t swayed by fluctuations in the dollar exchange rate, I suggest using the `getRate` method in `OffchainOracle`. You can execute this directly in the [bscscan explorer](https://bscscan.com/address/0x0AdDd25a91563696D8567Df78D5A01C9a991F9B8#readContract) or programmatically, but **don't use it onchain**. This approach enables you to gauge the price of any token relative to another, thereby minimizing potential disparities and incongruities in prices amongst different services and sidestepping inaccuracies in the crypto-to-dollar valuation.

**Comment by zZoMROT** [comment]
Responding to the main question of the issue:
The `SpotPriceAggregator` returns the weighted price of one token to another at the current moment, taking into account various protocols (which can be viewed in the README of this repository) and settings (such as the connectors used, wrappers used, and a threshold filter that allows disregarding pools with low liquidity and incorrect rate).
